# Config Example
iOS:
    appID: 'iOS APP ID'
    appleID: 'APP Store Connect Apple ID (email)'
    password: 'APP Store Connect Apple ID Password'
    notifySlackBotToken: 'slack bot token for iOS new review message'
    notifySlackBotChannelID: 'slack bot target channel id for iOS new review message'
    ignoreKeywords: #list, Optional
        - 'Keyword 1'
        - 'Keyword 2'
android:
    packageName: 'Android Package Name'
    jsonKeyFileName: 'android_publisher_key.json' # Google service account key file, relative to config.yml file
    notifySlackBotToken: 'slack bot token for android new review message'
    notifySlackBotChannelID: 'slack bot target channel id for android new review message'
    ignoreKeywords: #list, Optional
        - 'Keyword 1'
        - 'Keyword 2'
setting:
    lang: "en"
    developerNotifySlackBotToken: 'slack bot token for debug message'
    developerNotifySlackBotChannelID: 'slack bot target channel id for debug message'