# Config Example
iOS:
    appID: 'iOS APP ID'
    appleID: 'APP Store Connect Apple ID (email)'
    password: 'APP Store Connect Apple ID Password'
    notifyWebHookUrl: 'slack webhook url for iOS new rewview message'
    ignoreKeywords: #list, Optional
        - 'Keyword 1'
        - 'Keyword 2'
    iconEmoji: ':dog:'
    username: 'ZReview Bot'
android:
    packageName: 'Android Package Name'
    jsonKeyFileName: 'android_publisher_key.json' # relative to config.yml file
    notifyWebHookUrl: 'slack webhook url for android new rewview message'
    ignoreKeywords: #list, Optional
        - 'Keyword 1'
        - 'Keyword 2'
    iconEmoji: ':dog:'
    username: 'ZReview Bot'
setting:
    lang: "en"
    developerNotifyWebHookUrl: 'slack webhook url for debug message'
